# -*- coding: utf-8 -*-
"""Analitik Teks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7-_0eU2VGjKviRCRjlL1NovkuJLPIes
"""

import pandas as pd

df = pd.read_csv("GojekAppReviewV4.0.0-V4.9.3_Cleaned.csv")
df.head()

df.shape

df.isnull().sum()

df = df.dropna(subset=["content"])

def map_sentiment(score):
    if score <= 2:
        return "negative"
    elif score == 3:
        return "neutral"
    else:
        return "positive"

df["sentiment"] = df["score"].apply(map_sentiment)

df["sentiment"].value_counts()

import matplotlib.pyplot as plt

df["sentiment"].value_counts().plot(kind="bar")
plt.title("Distribusi Kelas Sentimen")
plt.xlabel("Sentiment")
plt.ylabel("Jumlah Data")
plt.show()

df = df[["content", "sentiment"]]
df.head()

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df["label"] = label_encoder.fit_transform(df["sentiment"])

label_encoder.classes_

from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    random_state=42,
    stratify=df["label"]
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42,
    stratify=temp_df["label"]
)

len(train_df), len(val_df), len(test_df)

from transformers import AutoTokenizer

tokenizer_indobert = AutoTokenizer.from_pretrained(
    "indobenchmark/indobert-base-p1"
)

def tokenize_function(examples, tokenizer):
    return tokenizer(
        examples["content"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
val_dataset   = Dataset.from_pandas(val_df)
test_dataset  = Dataset.from_pandas(test_df)

train_indobert = train_dataset.map(
    lambda x: tokenize_function(x, tokenizer_indobert),
    batched=True
)

val_indobert = val_dataset.map(
    lambda x: tokenize_function(x, tokenizer_indobert),
    batched=True
)

test_indobert = test_dataset.map(
    lambda x: tokenize_function(x, tokenizer_indobert),
    batched=True
)

columns = ["input_ids", "attention_mask", "label"]

train_indobert.set_format(type="torch", columns=columns)
val_indobert.set_format(type="torch", columns=columns)
test_indobert.set_format(type="torch", columns=columns)

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "indobenchmark/indobert-base-p1",
    num_labels=3
)

import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="weighted"
    )
    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results_indobert",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_indobert,
    eval_dataset=val_indobert,
    compute_metrics=compute_metrics
)

trainer.train()

test_results = trainer.evaluate(test_indobert)
test_results

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

predictions = trainer.predict(test_indobert)
y_pred = np.argmax(predictions.predictions, axis=1)
y_true = predictions.label_ids

cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=label_encoder.classes_
)

disp.plot(cmap="Blues")
plt.title("Confusion Matrix IndoBERT")
plt.show()

def load_indobert_model():
    return AutoModelForSequenceClassification.from_pretrained(
        "indobenchmark/indobert-base-p1",
        num_labels=3
    )

from transformers import TrainingArguments, Trainer

training_args_lr_small = TrainingArguments(
    output_dir="./results_lr_small",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=1e-5,  # lebih kecil
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs_lr_small",
    load_best_model_at_end=True
)

trainer_lr_small = Trainer(
    model=load_indobert_model(),
    args=training_args_lr_small,
    train_dataset=train_indobert,
    eval_dataset=val_indobert,
    compute_metrics=compute_metrics
)

trainer_lr_small.train()

eval_lr_small = trainer_lr_small.evaluate(test_indobert)
eval_lr_small

training_args_bs_small = TrainingArguments(
    output_dir="./results_bs_small",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,   # batch size kecil
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs_bs_small",
    load_best_model_at_end=True
)

trainer_bs_small = Trainer(
    model=load_indobert_model(),
    args=training_args_bs_small,
    train_dataset=train_indobert,
    eval_dataset=val_indobert,
    compute_metrics=compute_metrics
)

trainer_bs_small.train()

eval_bs_small = trainer_bs_small.evaluate(test_indobert)
eval_bs_small

import pandas as pd

comparison_df = pd.DataFrame([
    {
        "Eksperimen": "Baseline (LR=2e-5, BS=16)",
        "Accuracy": test_results["eval_accuracy"],
        "Precision": test_results["eval_precision"],
        "Recall": test_results["eval_recall"],
        "F1": test_results["eval_f1"]
    },
    {
        "Eksperimen": "LR kecil (1e-5, BS=16)",
        "Accuracy": eval_lr_small["eval_accuracy"],
        "Precision": eval_lr_small["eval_precision"],
        "Recall": eval_lr_small["eval_recall"],
        "F1": eval_lr_small["eval_f1"]
    },
    {
        "Eksperimen": "BS kecil (LR=2e-5, BS=8)",
        "Accuracy": eval_bs_small["eval_accuracy"],
        "Precision": eval_bs_small["eval_precision"],
        "Recall": eval_bs_small["eval_recall"],
        "F1": eval_bs_small["eval_f1"]
    }
])

comparison_df